version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "resume-challenge-backend"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1l6val0vvurua"
s3_prefix = "resume-challenge-backend"
region = "us-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
